#!/usr/bin/env bash
# Deploy Ekaette backend to Cloud Run WITH env vars.
#
# Usage:
#   ./scripts/deploy_cloudrun.sh            # build + deploy + set env vars
#   ./scripts/deploy_cloudrun.sh --env-only # update env vars without rebuilding
#
# This script ensures env vars are never wiped by a bare `gcloud run deploy --source .`.
# It reads from .env, filters out SIP bridge / WA bridge VM-only vars, converts to YAML,
# and applies via --env-vars-file.

set -euo pipefail

PROJECT="ekaette"
REGION="us-central1"
SERVICE="ekaette"
PORT="8000"
TIMEOUT="${TIMEOUT:-3600}"
MEMORY="${MEMORY:-1Gi}"
CPU="${CPU:-2}"
CONCURRENCY="${CONCURRENCY:-80}"
ALLOW_UNAUTHENTICATED="${ALLOW_UNAUTHENTICATED:-1}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/.env"
TMP_YAML="/tmp/ekaette_cloudrun_env.yaml"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: $ENV_FILE not found" >&2
  exit 1
fi

echo "==> Generating Cloud Run env vars from .env ..."

python3 - "$ENV_FILE" "$TMP_YAML" <<'PY'
from __future__ import annotations

import pathlib
import json
import re
import sys


env_file = pathlib.Path(sys.argv[1])
tmp_yaml = pathlib.Path(sys.argv[2])

# Patterns for VM-only env vars (SIP bridge, WA bridge runtime)
SKIP_PREFIXES = (
    "SIP_BRIDGE_HOST", "SIP_BRIDGE_PORT", "SIP_PUBLIC_IP", "SIP_REGISTRAR",
    "SIP_USERNAME", "SIP_PASSWORD", "SIP_REGISTER_", "SIP_HEALTH_",
    "SIP_RTP_", "SIP_ALLOWED_", "SIP_SYSTEM_",
    "WA_SIP_", "WA_GATEWAY_", "WA_LIVE_MODEL", "WA_SYSTEM_",
    "WA_GEMINI_", "WA_SANDBOX_", "WA_HEALTH_", "WA_COMPANY_",
    "WA_TENANT_",
    "GATEWAY_MODE", "GATEWAY_WS_",
)
RESERVED = {"PORT"}
assignment_re = re.compile(r"^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$")


def normalize_value(raw: str) -> str:
    value = raw.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        value = value[1:-1]
    return value


def yaml_quote(raw: str) -> str:
    return json.dumps(raw, ensure_ascii=False)[1:-1]


envs: dict[str, str] = {}
for raw_line in env_file.read_text(encoding="utf-8").splitlines():
    line = raw_line.strip()
    if not line or line.startswith("#"):
        continue
    match = assignment_re.match(line)
    if match is None:
        continue
    key, raw_value = match.groups()
    value = normalize_value(raw_value)
    if not value:
        continue
    if key in RESERVED:
        continue
    if any(key.startswith(prefix) for prefix in SKIP_PREFIXES):
        continue
    envs[key] = value

# Cloud Run WebSocket clients such as the SIP and WA gateways may connect
# without an Origin header. Tighten ALLOWED_ORIGINS and revisit the websocket
# checks in app/api/v1/public/core_helpers.py and app/api/v1/realtime/session_init.py
# before disabling or narrowing this override.
added_missing_origin_default = "ALLOW_MISSING_WS_ORIGIN" not in envs
if added_missing_origin_default:
    envs["ALLOW_MISSING_WS_ORIGIN"] = "true"

with tmp_yaml.open("w", encoding="utf-8") as handle:
    handle.write("# Generated by scripts/deploy_cloudrun.sh\n")
    if added_missing_origin_default:
        handle.write(
            "# Defaulted ALLOW_MISSING_WS_ORIGIN for Cloud Run websocket clients "
            "that omit an Origin header.\n"
        )
    for key in sorted(envs):
        handle.write(f'{key}: "{yaml_quote(envs[key])}"\n')

print(f"  {len(envs)} env vars written to {tmp_yaml}")
PY

DEPLOY_AUTH_FLAG=(--allow-unauthenticated)
UPDATE_AUTH_FLAG=(--no-invoker-iam-check)
if [[ "$ALLOW_UNAUTHENTICATED" != "1" ]]; then
  DEPLOY_AUTH_FLAG=(--no-allow-unauthenticated)
  UPDATE_AUTH_FLAG=(--invoker-iam-check)
fi

if [[ "${1:-}" == "--env-only" ]]; then
  echo "==> Updating env vars only (no rebuild) ..."
  gcloud run services update "$SERVICE" \
    --project "$PROJECT" \
    --region "$REGION" \
    --port="$PORT" \
    --timeout="$TIMEOUT" \
    --memory="$MEMORY" \
    --cpu="$CPU" \
    --concurrency="$CONCURRENCY" \
    --env-vars-file="$TMP_YAML" \
    "${UPDATE_AUTH_FLAG[@]}" \
    --quiet
else
  echo "==> Building and deploying ..."
  gcloud run deploy "$SERVICE" \
    --source "$ROOT_DIR" \
    --project "$PROJECT" \
    --region "$REGION" \
    --port="$PORT" \
    --timeout="$TIMEOUT" \
    --memory="$MEMORY" \
    --cpu="$CPU" \
    --concurrency="$CONCURRENCY" \
    --env-vars-file="$TMP_YAML" \
    "${DEPLOY_AUTH_FLAG[@]}" \
    --quiet
fi

SERVICE_URL="$(gcloud run services describe "$SERVICE" --project "$PROJECT" --region "$REGION" --format='value(status.url)' 2>/dev/null || true)"
if [[ -n "$SERVICE_URL" ]]; then
  echo "==> Done. Service URL: $SERVICE_URL"
else
  PROJECT_NUMBER="$(gcloud projects describe "$PROJECT" --format='value(projectNumber)' 2>/dev/null || true)"
  if [[ -n "$PROJECT_NUMBER" ]]; then
    echo "==> Done. Service URL: https://${SERVICE}-${PROJECT_NUMBER}.${REGION}.run.app"
  else
    echo "==> Done. Unable to resolve the Cloud Run URL automatically for ${SERVICE} in ${REGION}."
  fi
fi
