name: OSV-Scanner

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  security-events: write
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: OSV-Scanner
        uses: google/osv-scanner-action/osv-scanner-action@764c91816374ff2d8fc2095dab36eecd42d61638 # v1.9.2
        with:
          scan-args: -r --skip-git ./
